// 模拟数据 - 头像使用本地 PNG，无需网络

const mockUsers = [
  {
    _id: 'user_001',
    openid: 'mock_openid_001',
    nickName: '球神小李',
    avatarUrl: '/images/avatar-1.png',
    gender: 1,
    city: '上海',
    district: '浦东新区',
    level: 'P4',
    levelVerified: true,
    creditScore: 92,
    gamesPlayed: 47,
    bio: '打球5年，热爱匹克球，周末随时约！',
    createdAt: '2024-01-15',
  },
  {
    _id: 'user_002',
    openid: 'mock_openid_002',
    nickName: '娜娜球球',
    avatarUrl: '/images/avatar-2.png',
    gender: 2,
    city: '上海',
    district: '徐汇区',
    level: 'P3',
    levelVerified: true,
    creditScore: 85,
    gamesPlayed: 23,
    bio: '喜欢和大家一起打球，进步中～',
    createdAt: '2024-02-20',
  },
  {
    _id: 'user_003',
    openid: 'mock_openid_003',
    nickName: '老王打球',
    avatarUrl: '/images/avatar-3.png',
    gender: 1,
    city: '上海',
    district: '静安区',
    level: 'P5',
    levelVerified: true,
    creditScore: 96,
    gamesPlayed: 128,
    bio: 'P5+，喜欢竞技对抗，寻找同水平球友',
    createdAt: '2023-08-10',
  },
  {
    _id: 'user_004',
    openid: 'mock_openid_004',
    nickName: '小白一枚',
    avatarUrl: '/images/avatar-4.png',
    gender: 1,
    city: '上海',
    district: '长宁区',
    level: 'P2',
    levelVerified: false,
    creditScore: 80,
    gamesPlayed: 3,
    bio: '新手上路，多多包涵！',
    createdAt: '2024-05-01',
  },
  {
    _id: 'user_005',
    openid: 'mock_openid_005',
    nickName: '陈教练',
    avatarUrl: '/images/avatar-5.png',
    gender: 1,
    city: '上海',
    district: '杨浦区',
    level: 'P6',
    levelVerified: true,
    creditScore: 98,
    gamesPlayed: 312,
    bio: '职业教练，承接教学培训，欢迎各水平球友',
    createdAt: '2023-01-01',
  },
];

const mockGames = [
  {
    _id: 'game_001',
    creatorId: 'user_003',
    creator: mockUsers[2],
    title: '周末双打友谊赛',
    description: '4人双打，欢迎P3-P5水平球友，氛围友好，比完一起吃饭！',
    venue: '古北网球匹克球中心',
    address: '上海市长宁区古北路888号',
    city: '上海',
    district: '长宁区',
    date: '2026-05-31',
    startTime: '09:00',
    endTime: '11:00',
    maxPlayers: 4,
    currentPlayers: 2,
    minLevel: 'P3',
    maxLevel: 'P5',
    fee: 60,
    status: 'OPEN',
    participants: [mockUsers[2], mockUsers[1]],
    createdAt: '2026-05-20',
  },
  {
    _id: 'game_002',
    creatorId: 'user_001',
    creator: mockUsers[0],
    title: '工作日早鸟局',
    description: '早上7点开始，P2以上均可，欢迎新手！带拍可借',
    venue: '浦东体育中心',
    address: '上海市浦东新区浦东南路1800号',
    city: '上海',
    district: '浦东新区',
    date: '2026-05-27',
    startTime: '07:00',
    endTime: '09:00',
    maxPlayers: 6,
    currentPlayers: 5,
    minLevel: 'P2',
    maxLevel: 'P6',
    fee: 40,
    status: 'OPEN',
    participants: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3], mockUsers[4]],
    createdAt: '2026-05-19',
  },
  {
    _id: 'game_003',
    creatorId: 'user_005',
    creator: mockUsers[4],
    title: '周三下午混双训练',
    description: '训练为主，有陈教练带队，重点练习发球和第三球',
    venue: '虹桥匹克球俱乐部',
    address: '上海市闵行区虹梅路2080号',
    city: '上海',
    district: '闵行区',
    date: '2026-05-28',
    startTime: '14:00',
    endTime: '17:00',
    maxPlayers: 8,
    currentPlayers: 8,
    minLevel: 'P3',
    maxLevel: 'P6',
    fee: 80,
    status: 'FULL',
    participants: mockUsers,
    createdAt: '2026-05-18',
  },
  {
    _id: 'game_004',
    creatorId: 'user_002',
    creator: mockUsers[1],
    title: '新手友好局，一起进步',
    description: '纯新手场，大家一起学习基本规则，互相切磋，不评级不评判',
    venue: '徐汇体育公园',
    address: '上海市徐汇区漕溪北路399号',
    city: '上海',
    district: '徐汇区',
    date: '2026-06-01',
    startTime: '16:00',
    endTime: '18:00',
    maxPlayers: 6,
    currentPlayers: 1,
    minLevel: 'P1',
    maxLevel: 'P2',
    fee: 30,
    status: 'OPEN',
    participants: [mockUsers[1]],
    createdAt: '2026-05-21',
  },
  {
    _id: 'game_005',
    creatorId: 'user_003',
    creator: mockUsers[2],
    title: '上周四夜场对打（已结束）',
    description: '四人单循环，氛围很好，下次继续！',
    venue: '静安体育中心',
    address: '上海市静安区江宁路166号',
    city: '上海',
    district: '静安区',
    date: '2026-05-22',
    startTime: '19:00',
    endTime: '21:00',
    maxPlayers: 4,
    currentPlayers: 4,
    minLevel: 'P3',
    maxLevel: 'P5',
    fee: 50,
    status: 'COMPLETED',
    participants: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3]],
    createdAt: '2026-05-18',
  },
];

const mockCreditLogs = [
  { _id: 'log_001', userId: 'user_001', change: 2, reason: '准时到场', gameId: 'game_005', newScore: 92, createdAt: '2026-05-22' },
  { _id: 'log_002', userId: 'user_001', change: 5, reason: '连续3次准时奖励', gameId: 'game_003', newScore: 90, createdAt: '2026-05-15' },
  { _id: 'log_003', userId: 'user_001', change: 2, reason: '获得好评', gameId: 'game_002', newScore: 85, createdAt: '2026-05-10' },
  { _id: 'log_004', userId: 'user_001', change: -5, reason: '迟到15分钟以上', gameId: 'game_001', newScore: 83, createdAt: '2026-05-05' },
];

const mockMessages = [
  {
    _id: 'msg_001',
    type: 'system',
    title: '球局提醒',
    content: '您的球局「周末双打友谊赛」将于5月31日09:00开始，请准时到场！',
    gameId: 'game_001',
    isRead: false,
    createdAt: '2026-05-30 08:00',
  },
  {
    _id: 'msg_002',
    type: 'join_request',
    title: '加入申请',
    content: '小白一枚 申请加入您的球局「工作日早鸟局」',
    gameId: 'game_002',
    fromUserId: 'user_004',
    fromUser: mockUsers[3],
    isRead: false,
    createdAt: '2026-05-25 14:30',
  },
  {
    _id: 'msg_003',
    type: 'review',
    title: '收到新评价',
    content: '老王打球 给您评价了：准时守信、球技出色',
    fromUserId: 'user_003',
    fromUser: mockUsers[2],
    isRead: true,
    createdAt: '2026-05-22 21:00',
  },
  {
    _id: 'msg_004',
    type: 'approved',
    title: '申请已通过',
    content: '您申请加入「周三下午混双训练」已通过，请准时参加！',
    gameId: 'game_003',
    isRead: true,
    createdAt: '2026-05-19 11:00',
  },
];

const mockReviews = [
  {
    _id: 'review_001',
    gameId: 'game_005',
    reviewerId: 'user_003',
    reviewer: mockUsers[2],
    revieweeId: 'user_001',
    rating: 5,
    tags: ['准时守信', '球技出色', '态度友好'],
    comment: '小李打球很稳，也很守时，下次还要一起！',
    isPunctual: true,
    createdAt: '2026-05-22',
  },
  {
    _id: 'review_002',
    gameId: 'game_002',
    reviewerId: 'user_005',
    reviewer: mockUsers[4],
    revieweeId: 'user_001',
    rating: 4,
    tags: ['球技出色', '遵守规则'],
    comment: '技术不错，继续保持！',
    isPunctual: true,
    createdAt: '2026-05-15',
  },
];

// 记录已提交的评价（用于判断是否已评价）
const submittedReviews = {};

// 当前登录用户（user_001 = 球神小李）
const currentUser = mockUsers[0];

module.exports = {
  mockUsers,
  mockGames,
  mockCreditLogs,
  mockMessages,
  mockReviews,
  submittedReviews,
  currentUser,
};
